package com.mycompany.lab7_121;

import com.mycompany.lab7_121.MyDate;
import com.mycompany.lab7_121.PolicyException;
import com.mycompany.lab7_121.policyHolderNameException;
import com.mycompany.lab7_121.ThirdPartyPolicy;
import com.mycompany.lab7_121.User;
import com.mycompany.lab7_121.UserUI;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author qdaon
 */
public class Login extends javax.swing.JFrame {

    static InsuranceCompany myCompany;
    /**
     * Creates new form LogIn
     */
    public Login() throws PolicyException, policyHolderNameException {
        this.myCompany = new InsuranceCompany();
        test();
        initComponents();
    }
    
     public void test() throws PolicyException, policyHolderNameException {
        this.myCompany = new InsuranceCompany("Nobita LTD", "nobita", "nobita", 12);
        final Car car1 = new Car("Toyota Camry", CarType.SED, 2022, 40000);
        final Car car2 = new Car("Honda Civic", CarType.HATCH, 2021, 60000);
        final Car car3 = new Car("Porsche 911", CarType.LUX, 2023, 100000);
        final Car car4 = new Car("Toyota Land Cruiser", CarType.SUV, 2020, 50000);
        final ComprehensivePolicy policy1 = new ComprehensivePolicy("Jane", 200, car1, 10, new MyDate(10,2,2025), 19, 1);
        final ThirdPartyPolicy policy2 = new ThirdPartyPolicy("Tom", 201, car3, 10, new MyDate(15,12,2024), "Value Customer");
        final ComprehensivePolicy policy3 = new ComprehensivePolicy("Dao", 202, car2, 10, new MyDate(14,2,2025), 31, 3);
        final ThirdPartyPolicy policy4 = new ThirdPartyPolicy("Bob", 203, car4, 10, new MyDate(1,1,2025), "Bad Customer");
        final ComprehensivePolicy policy5 = new ComprehensivePolicy("James", 204, car1, 10, new MyDate(7,8,2025), 25, 2);
        final ThirdPartyPolicy policy6 = new ThirdPartyPolicy("Chau", 205, car2, 10, new MyDate(10,6,2025), "Old Customer");
        final User user1 = new User("Jane", new Address(13, "Derwent St", "Lyons", "Canberra"), "1");
        final User user2 = new User("Tom", new Address(1, "Porter St", "North Wollongong", "Wollongong"), "1");
        final User user3 = new User("Dao", new Address(10, "Victoria St", "Wollongong", "Wollongong"), "1");
        final User user4 = new User("Bob", new Address(1, "Hindmarsh St", "North Wollongong", "Wollongong"), "1");
        final User user5 = new User("James", new Address(69, "Rocks St", "Central", "Sydney"), "1");
        final User user6 = new User("Chau", new Address(10, "Crown St", "Parkville", "Melbourne"), "1");
        this.myCompany.addUser(user1);
        this.myCompany.addUser(user2);
        this.myCompany.addUser(user3);
        this.myCompany.addUser(user4);
        this.myCompany.addUser(user5);
        this.myCompany.addUser(user6);
        this.myCompany.addPolicy(user1.getUserID(), policy1);
        this.myCompany.addPolicy(user1.getUserID(), policy2);
        this.myCompany.addPolicy(user1.getUserID(), policy3);
        this.myCompany.addPolicy(user2.getUserID(), policy4);
        this.myCompany.addPolicy(user2.getUserID(), policy5);
        this.myCompany.addPolicy(user2.getUserID(), policy6);
        this.myCompany.addPolicy(user3.getUserID(), policy1);
        this.myCompany.addPolicy(user3.getUserID(), policy2);
        this.myCompany.addPolicy(user3.getUserID(), policy3);
        this.myCompany.addPolicy(user4.getUserID(), policy4);
        this.myCompany.addPolicy(user4.getUserID(), policy5);
        this.myCompany.addPolicy(user4.getUserID(), policy6);
        this.myCompany.addPolicy(user5.getUserID(), policy1);
        this.myCompany.addPolicy(user5.getUserID(), policy2);
        this.myCompany.addPolicy(user5.getUserID(), policy3);
        this.myCompany.addPolicy(user6.getUserID(), policy4);
        this.myCompany.addPolicy(user6.getUserID(), policy5);
        this.myCompany.addPolicy(user6.getUserID(), policy6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        load = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        listOfUsers = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username.setText("Username");

        password.setText("Password");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        file.setText("File");

        load.setText("Load");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });
        file.add(load);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        file.add(save);

        menuBar.add(file);

        listOfUsers.setText("List Of Users");
        listOfUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listOfUsersMouseClicked(evt);
            }
        });
        menuBar.add(listOfUsers);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login)
                    .addComponent(usernameField)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(login)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        // TODO add your handling code here:
        if (myCompany.load("company.ser")) {
            JOptionPane.showMessageDialog(this, "Load data from file " + "company.ser" + " done.");
        }
    }//GEN-LAST:event_loadActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(myCompany.save("company.ser")) {
            JOptionPane.showMessageDialog(this, "Save data to file " + "company.ser" + " done.");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        this.login();
    }//GEN-LAST:event_loginActionPerformed
 
    private void listOfUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listOfUsersMouseClicked
        // TODO add your handling code here:
         String output = "";
        for (final User user : myCompany.getUsers().values()) {
            output = output + "username: " + user.getName() + " pass: " + user.getPassword() + "\n";
        }
        JOptionPane.showMessageDialog(this, output);
    }//GEN-LAST:event_listOfUsersMouseClicked

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
        this.login();
    }//GEN-LAST:event_passwordFieldActionPerformed

    public void login() {
        String username = usernameField.getText().trim();
        String password = String.valueOf(passwordField.getText()).trim();
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username or password is wrong.");
            return;
        }
        if (myCompany.validateAdmin(username, password)) {
            this.setVisible(false);
            final ArrayList<Integer>userID = new ArrayList<>();
            for (int id : myCompany.getUsers().keySet()) {
                userID.add(id);
            }
            final ArrayList<String> cities = this.myCompany.populateDistinctCityNames();
            AdminUI adminUI = new AdminUI(myCompany, this, cities, userID);
            adminUI.setVisible(true);
        }
        else {
            if (username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username or password is wrong");
                return;
            }
            
            User user = myCompany.validateUser(username, password);
            if (user != null) {
                final ArrayList<String> cities = this.myCompany.populateDistinctCityNames();
                UserUI userUI = new UserUI (user, this, cities);
                this.setVisible(false);
                userUI.setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(this, "Username or password is wrong");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (PolicyException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (policyHolderNameException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu file;
    private javax.swing.JMenu listOfUsers;
    private javax.swing.JMenuItem load;
    private javax.swing.JButton login;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel password;
    private javax.swing.JTextField passwordField;
    private javax.swing.JMenuItem save;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
