package com.mycompany.lab7_121;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author qdaon
 */

public class PolicyException extends Exception {
    private int id;
    public PolicyException(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public String toString() {
        return "Policy ID was not valid and a new ID (" +id+ ") is generated by admin and assigned for the Policy.";
    }
}


