package com.mycompany.lab7_121;

import java.util.List;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.JOptionPane;
import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.MouseListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseAdapter;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.AbstractButton;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.LayoutStyle;
import java.awt.Component;
import java.awt.LayoutManager;
import java.awt.Container;
import javax.swing.GroupLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.FocusListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusAdapter;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.Font;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTabbedPane;
import javax.swing.JScrollPane;
import javax.swing.JPanel;
import javax.swing.JMenuItem;
import javax.swing.JMenuBar;
import javax.swing.JMenu;
import javax.swing.JComboBox;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import java.util.ArrayList;
import javax.swing.JFrame;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author qdaon
 */
public class UserUI extends javax.swing.JFrame {

    /**
     * Creates new form UserUI
     */
    ArrayList<String> cities;
    User user;
    Login login;
    
    public UserUI(final User user, final Login login, final ArrayList<String> cities) {
        this.user = user;
        this.login = login;
        this.cities = cities;
        initComponents();
    }

    UserUI(boolean user, Login aThis, ArrayList<String> cities) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        jPanelEditPersonalData = new javax.swing.JPanel();
        userIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        userIDText = new javax.swing.JTextField();
        usernameText = new javax.swing.JTextField();
        passText = new javax.swing.JTextField();
        jLabelAddInfo = new javax.swing.JLabel();
        strNumLabel = new javax.swing.JLabel();
        strLabel = new javax.swing.JLabel();
        suburbLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        strNumText = new javax.swing.JTextField();
        strText = new javax.swing.JTextField();
        suburbText = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        checkBoxNewCity = new javax.swing.JCheckBox();
        comboBoxCity = new javax.swing.JComboBox<>();
        jButtonChange = new javax.swing.JButton();
        jPanelAddPolicies = new javax.swing.JPanel();
        jLabelPolicyID = new javax.swing.JLabel();
        tppRadio = new javax.swing.JRadioButton();
        cpRadio = new javax.swing.JRadioButton();
        policyIDText = new javax.swing.JTextField();
        jLabelPlcHolderName = new javax.swing.JLabel();
        policyNameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        modelText = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox<>();
        jLabelmanuYear = new javax.swing.JLabel();
        manufacturingYearText = new javax.swing.JTextField();
        jLabelPrice = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numberOfClaimsText = new javax.swing.JTextField();
        jLabelExpiryData = new javax.swing.JLabel();
        jLabelDay = new javax.swing.JLabel();
        dayText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        monthText = new javax.swing.JTextField();
        jLabelYear = new javax.swing.JLabel();
        yearText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        commentAgeLabel = new javax.swing.JLabel();
        commentAgeText = new javax.swing.JTextField();
        levelLabel = new javax.swing.JLabel();
        levelText = new javax.swing.JTextField();
        jPanelFindPolicy = new javax.swing.JPanel();
        jLabelPlanID = new javax.swing.JLabel();
        planIDText = new javax.swing.JTextField();
        FindButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        policyArea = new javax.swing.JTextArea();
        jPanelPoliciesInformation = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        policyTable = new javax.swing.JTable();
        jPanelFilterPolicies = new javax.swing.JPanel();
        carModelLabel = new javax.swing.JLabel();
        carModelText = new javax.swing.JTextField();
        expiryDateFilterLabel = new javax.swing.JLabel();
        expiryDateFilterText = new javax.swing.JTextField();
        filterDateButton = new javax.swing.JButton();
        sortNameCheckbox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        policyTable1 = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });

        userIDLabel.setText("User ID");

        nameLabel.setText("Name");

        passLabel.setText("Password");

        userIDText.setEditable(false);
        userIDText.setEnabled(false);
        userIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDTextActionPerformed(evt);
            }
        });

        usernameText.setEditable(false);
        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });

        passText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTextActionPerformed(evt);
            }
        });

        jLabelAddInfo.setText("Address Information");

        strNumLabel.setText("Street Number");

        strLabel.setText("Street");

        suburbLabel.setText("Suburb");

        cityLabel.setText("City");

        strNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strNumTextActionPerformed(evt);
            }
        });

        strText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strTextActionPerformed(evt);
            }
        });

        suburbText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suburbTextActionPerformed(evt);
            }
        });

        cityText.setEnabled(false);
        cityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextActionPerformed(evt);
            }
        });

        checkBoxNewCity.setText("New City");
        checkBoxNewCity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxNewCityStateChanged(evt);
            }
        });
        checkBoxNewCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxNewCityActionPerformed(evt);
            }
        });

        comboBoxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wollongong", "Sydney", "Melbourne", "Canberra" }));
        comboBoxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCityActionPerformed(evt);
            }
        });

        jButtonChange.setText("Change");
        jButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditPersonalDataLayout = new javax.swing.GroupLayout(jPanelEditPersonalData);
        jPanelEditPersonalData.setLayout(jPanelEditPersonalDataLayout);
        jPanelEditPersonalDataLayout.setHorizontalGroup(
            jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditPersonalDataLayout.createSequentialGroup()
                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditPersonalDataLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEditPersonalDataLayout.createSequentialGroup()
                                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userIDText)
                                    .addComponent(passText)
                                    .addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))))
                    .addGroup(jPanelEditPersonalDataLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonChange)
                            .addGroup(jPanelEditPersonalDataLayout.createSequentialGroup()
                                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(strNumLabel)
                                    .addComponent(strLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(suburbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(strNumText)
                                    .addComponent(strText)
                                    .addComponent(suburbText)
                                    .addComponent(comboBoxCity, 0, 108, Short.MAX_VALUE))
                                .addGap(17, 17, 17)
                                .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxNewCity, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        jPanelEditPersonalDataLayout.setVerticalGroup(
            jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditPersonalDataLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIDLabel)
                    .addComponent(userIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelAddInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strNumLabel)
                    .addComponent(strNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strLabel)
                    .addComponent(strText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suburbLabel)
                    .addComponent(suburbText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxNewCity)
                    .addComponent(comboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButtonChange)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Edit Personal Data", jPanelEditPersonalData);

        jLabelPolicyID.setText("Policy ID");

        tppRadio.setSelected(true);
        tppRadio.setText("Third Pary Policy");
        tppRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tppRadioStateChanged(evt);
            }
        });

        cpRadio.setText("Comprehensive Policy");
        cpRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cpRadioStateChanged(evt);
            }
        });

        jLabelPlcHolderName.setText("Policy Holder Name");

        jLabel1.setText("Model");

        jLabelType.setText("Type");

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SED", "SUV", "LUX", "HATCH" }));

        jLabelmanuYear.setText("Manufacturing Year");

        jLabelPrice.setText("Price");

        jLabel2.setText("Number Of Claims ");

        jLabelExpiryData.setText("Expiry Date");

        jLabelDay.setText("Day");

        jLabel3.setText("Month");

        jLabelYear.setText("Year");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        commentAgeLabel.setText("Comments");

        levelLabel.setText("Level");

        javax.swing.GroupLayout jPanelAddPoliciesLayout = new javax.swing.GroupLayout(jPanelAddPolicies);
        jPanelAddPolicies.setLayout(jPanelAddPoliciesLayout);
        jPanelAddPoliciesLayout.setHorizontalGroup(
            jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddPoliciesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAddPoliciesLayout.createSequentialGroup()
                        .addComponent(tppRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanelAddPoliciesLayout.createSequentialGroup()
                        .addComponent(jLabelPolicyID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(policyIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(484, 484, 484))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddPoliciesLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAddPoliciesLayout.createSequentialGroup()
                        .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelPlcHolderName)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelmanuYear, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabelExpiryData)
                                .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(policyNameText)
                            .addComponent(modelText)
                            .addComponent(typeCombo, 0, 116, Short.MAX_VALUE)
                            .addComponent(manufacturingYearText)
                            .addComponent(priceText)
                            .addComponent(numberOfClaimsText)))
                    .addGroup(jPanelAddPoliciesLayout.createSequentialGroup()
                        .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelYear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commentAgeLabel)
                            .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dayText)
                            .addComponent(monthText)
                            .addComponent(yearText, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(commentAgeText)
                            .addComponent(levelText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAddPoliciesLayout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(19, 19, 19)))
                .addGap(142, 142, 142)
                .addComponent(clearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddPoliciesLayout.setVerticalGroup(
            jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddPoliciesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tppRadio)
                    .addComponent(cpRadio))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPolicyID)
                    .addComponent(policyIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlcHolderName)
                    .addComponent(policyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmanuYear)
                    .addComponent(manufacturingYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfClaimsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelExpiryData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDay)
                    .addComponent(dayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(monthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYear)
                    .addComponent(yearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commentAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commentAgeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(levelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(addButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Add policies", jPanelAddPolicies);

        jLabelPlanID.setText("Policy ID");

        planIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planIDTextActionPerformed(evt);
            }
        });

        FindButton.setText("FIND");
        FindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindButtonActionPerformed(evt);
            }
        });

        policyArea.setColumns(20);
        policyArea.setRows(5);
        jScrollPane1.setViewportView(policyArea);

        javax.swing.GroupLayout jPanelFindPolicyLayout = new javax.swing.GroupLayout(jPanelFindPolicy);
        jPanelFindPolicy.setLayout(jPanelFindPolicyLayout);
        jPanelFindPolicyLayout.setHorizontalGroup(
            jPanelFindPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFindPolicyLayout.createSequentialGroup()
                .addGroup(jPanelFindPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFindPolicyLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelPlanID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(planIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FindButton))
                    .addGroup(jPanelFindPolicyLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanelFindPolicyLayout.setVerticalGroup(
            jPanelFindPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFindPolicyLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelFindPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlanID)
                    .addComponent(planIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Find a Policy", jPanelFindPolicy);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        policyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(policyTable);

        javax.swing.GroupLayout jPanelPoliciesInformationLayout = new javax.swing.GroupLayout(jPanelPoliciesInformation);
        jPanelPoliciesInformation.setLayout(jPanelPoliciesInformationLayout);
        jPanelPoliciesInformationLayout.setHorizontalGroup(
            jPanelPoliciesInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPoliciesInformationLayout.createSequentialGroup()
                .addGroup(jPanelPoliciesInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPoliciesInformationLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(deleteButton)
                        .addGap(40, 40, 40)
                        .addComponent(updateButton))
                    .addGroup(jPanelPoliciesInformationLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanelPoliciesInformationLayout.setVerticalGroup(
            jPanelPoliciesInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPoliciesInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanelPoliciesInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Policies Information", jPanelPoliciesInformation);

        jPanelFilterPolicies.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelFilterPoliciesFocusGained(evt);
            }
        });

        carModelLabel.setText("Car Model");

        carModelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carModelTextActionPerformed(evt);
            }
        });
        carModelText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                carModelTextKeyReleased(evt);
            }
        });

        expiryDateFilterLabel.setText("Expiry Date");

        expiryDateFilterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDateFilterTextActionPerformed(evt);
            }
        });

        filterDateButton.setText("Filter by Date");
        filterDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterDateButtonActionPerformed(evt);
            }
        });

        sortNameCheckbox.setText("Sort by Users");
        sortNameCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortNameCheckboxActionPerformed(evt);
            }
        });

        policyTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(policyTable1);

        javax.swing.GroupLayout jPanelFilterPoliciesLayout = new javax.swing.GroupLayout(jPanelFilterPolicies);
        jPanelFilterPolicies.setLayout(jPanelFilterPoliciesLayout);
        jPanelFilterPoliciesLayout.setHorizontalGroup(
            jPanelFilterPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterPoliciesLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanelFilterPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carModelLabel)
                    .addComponent(expiryDateFilterLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelFilterPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carModelText)
                    .addComponent(expiryDateFilterText, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGroup(jPanelFilterPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilterPoliciesLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(filterDateButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilterPoliciesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortNameCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))))
            .addGroup(jPanelFilterPoliciesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        jPanelFilterPoliciesLayout.setVerticalGroup(
            jPanelFilterPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterPoliciesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanelFilterPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carModelLabel)
                    .addComponent(carModelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortNameCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFilterPoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiryDateFilterLabel)
                    .addComponent(expiryDateFilterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterDateButton))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Filter Policies", jPanelFilterPolicies);

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });
        menuBar.add(logout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void userIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDTextActionPerformed

    private void passTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextActionPerformed

    private void strNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strNumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strNumTextActionPerformed

    private void strTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strTextActionPerformed

    private void suburbTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suburbTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suburbTextActionPerformed

    private void comboBoxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCityActionPerformed

    private void cityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextActionPerformed

    private void checkBoxNewCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxNewCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxNewCityActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try {
            final int policyID = Integer.parseInt(policyIDText.getText());
            final String policyHolderName = policyNameText.getText();
            final String model = modelText.getText();
            final CarType type = CarType.valueOf(typeCombo.getSelectedItem().toString());
            final int manufacturingYear = Integer.parseInt(manufacturingYearText.getText());
            final double price = Double.parseDouble(priceText.getText());
            final int numberOfClaims = Integer.parseInt(numberOfClaimsText.getText());
            final int day = Integer.parseInt(dayText.getText());
            final int month = Integer.parseInt(monthText.getText());
            final int year = Integer.parseInt(yearText.getText());
            Car car = new Car(model, type, manufacturingYear, price);
            MyDate expiryDate = new MyDate(day, month, year);
            InsurancePolicy policy;
            if (tppRadio.isSelected()) {
                final String comments = commentAgeText.getText();
                policy = new ThirdPartyPolicy(policyHolderName, policyID, car, numberOfClaims, expiryDate, comments);
            }
            else {
                final int age = Integer.parseInt(commentAgeText.getText());
                final int level = Integer.parseInt(levelText.getText());
                policy = new ComprehensivePolicy(policyHolderName, policyID, car, numberOfClaims, expiryDate, age, level);
            }
            if (user.addPolicy(policy)) {
                JOptionPane.showMessageDialog(this, "Policy has been added");
                policyIDText.setText("");
                policyNameText.setText("");
                modelText.setText("");
                manufacturingYearText.setText("");
                priceText.setText("");
                numberOfClaimsText.setText("");
                dayText.setText("");
                monthText.setText("");
                yearText.setText("");
                commentAgeText.setText("");
                levelText.setText("");
            }
            else {
                JOptionPane.showMessageDialog(this, "Policy can not be added");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        policyIDText.setText("");
        policyNameText.setText("");
        modelText.setText("");
        manufacturingYearText.setText("");
        priceText.setText("");
        numberOfClaimsText.setText("");
        dayText.setText("");
        monthText.setText("");
        yearText.setText("");
        commentAgeText.setText("");
        levelText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void planIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planIDTextActionPerformed

    private void FindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindButtonActionPerformed
        // TODO add your handling code here:
        try {
            final InsurancePolicy policy = user.findPolicy(Integer.parseInt(planIDText.getText()));
            if (policy != null) {
                policyArea.append(policy.toString() + "\n");
            }
            else {
                policyArea.append("Policy with ID= " + this.planIDText.getText() + " has not been found \n");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_FindButtonActionPerformed

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        this.dispose();
        this.login.setVisible(true);
    }//GEN-LAST:event_logoutMousePressed

    private void jButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeActionPerformed
        // TODO add your handling code here:
        try {
            user.setName(usernameText.getText());
            user.setPassword(passText.getText());
            user.getAddress().setStreetNum(Integer.parseInt(strNumText.getText()));
            user.getAddress().setStreet(strText.getText());
            user.getAddress().setSuburb(suburbText.getText());
            if (checkBoxNewCity.isSelected()) {
                user.getAddress().setCity(cityText.getText());
                cities.add(cityText.getText());
                comboBoxCity.setModel(new DefaultComboBoxModel<String>(cities.toArray(new String[0])));
                comboBoxCity.setSelectedItem(cityText.getText());
            }
            else {
                user.getAddress().setCity((String) comboBoxCity.getSelectedItem());
                cityText.setText(this.user.getAddress().getCity());
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButtonChangeActionPerformed

    private void tppRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tppRadioStateChanged
        // TODO add your handling code here:
        if (tppRadio.isSelected()) {
            levelLabel.setVisible(false);
            levelText.setVisible(false);
            commentAgeLabel.setText("Comments");
            tppRadio.setSelected(true);
            cpRadio.setSelected(false);
        }
        else {
            levelLabel.setVisible(true);
            levelText.setVisible(true);
            commentAgeLabel.setText("Age");
            tppRadio.setSelected(false);
            cpRadio.setSelected(true);
        }
    }//GEN-LAST:event_tppRadioStateChanged

    private void carModelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carModelTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carModelTextActionPerformed

    private void expiryDateFilterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDateFilterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateFilterTextActionPerformed

    private void filterDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDateButtonActionPerformed
        // TODO add your handling code here:
        this.fillTable1();

    }//GEN-LAST:event_filterDateButtonActionPerformed

    private void checkBoxNewCityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxNewCityStateChanged
        // TODO add your handling code here
        if (checkBoxNewCity.isSelected()) {
            this.comboBoxCity.setEnabled(false);
            this.cityText.setEnabled(true);
        }
        else {
            this.comboBoxCity.setEnabled(true);
            this.cityText.setEnabled(false);
        }
    }//GEN-LAST:event_checkBoxNewCityStateChanged

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (policyTable.getSelectedRow() >=0) {
            int policyID = Integer.parseInt(policyTable.getModel().getValueAt(policyTable.getSelectedRow(), 0).toString());
            user.removePolicy(policyID);
            JOptionPane.showMessageDialog(this, "Policy " + policyID + " is deleted.");
            fillTable();
        }
        else {
            JOptionPane.showMessageDialog(this, "Please choose a policy to delete it");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void sortNameCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortNameCheckboxActionPerformed
        // TODO add your handling code here:
        this.fillTable1();
    }//GEN-LAST:event_sortNameCheckboxActionPerformed

    private void carModelTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carModelTextKeyReleased
        // TODO add your handling code here:
        this.fillTable1();
    }//GEN-LAST:event_carModelTextKeyReleased

    private void jPanelFilterPoliciesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelFilterPoliciesFocusGained
        // TODO add your handling code here:
        this.fillTable1();
    }//GEN-LAST:event_jPanelFilterPoliciesFocusGained

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if (policyTable.getSelectedRow() >=0) {
            int policyID = Integer.parseInt(policyTable.getModel().getValueAt(policyTable.getSelectedRow(), 0).toString());
            InsurancePolicy policy = user.findPolicy(policyID);
            final UpdateUI updateUI = new UpdateUI(policy, this);
            updateUI.setVisible(true);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneStateChanged
        // TODO add your handling code here:
        this.userIDText.setText(user.getUserID() + "");
        this.usernameText.setText(user.getName());
        this.passText.setText(user.getPassword());
        this.strNumText.setText(user.getAddress().getStreetNum() + "");
        this.strText.setText(user.getAddress().getStreet());
        this.suburbText.setText(user.getAddress().getSuburb());
        this.comboBoxCity.setModel(new DefaultComboBoxModel<String>(this.cities.toArray(new String[0])));
        this.comboBoxCity.setSelectedItem(user.getAddress().getCity());
        this.cityText.setText(user.getAddress().getCity());
        if (tppRadio.isSelected()) {
            levelLabel.setVisible(false);
            levelText.setVisible(false);
            commentAgeLabel.setText("Comments");
        }
        else {
            levelLabel.setVisible(true);
            levelText.setVisible(true);
            commentAgeLabel.setText("Age");
        }
        this.policyArea.setText("");
        // this.policyArea.setComponentPopupMenu();
        this.fillTable();
        this.fillTable1();
    }//GEN-LAST:event_tabbedPaneStateChanged

    private void cpRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cpRadioStateChanged
        // TODO add your handling code here:
        if (cpRadio.isSelected()) {
            levelLabel.setVisible(true);
            levelText.setVisible(true);
            commentAgeLabel.setText("Age");
            tppRadio.setSelected(false);
            cpRadio.setSelected(true);
        }
        else {
            levelLabel.setVisible(false);
            levelText.setVisible(false);
            commentAgeLabel.setText("Comments");
            tppRadio.setSelected(true);
            cpRadio.setSelected(false);
        }
    }//GEN-LAST:event_cpRadioStateChanged
    
    
    /**
     * @param args the command line arguments
     */

    public void fillTable() {
        final String[] header = {"Policy ID", "Policy Holder Name", "Car Model", "Car Type", "Manufacturing Year", "Price", "Number Of Claims", "Expiry Date", "Comments", "Driver Age", "Level", "Premium Payment"};
        final DefaultTableModel model = new DefaultTableModel(header, 0);
        policyTable.setModel(model);
        for (final InsurancePolicy policy : user.getPolicies().values()) {
            final String[] row = { policy.getId() +"", policy.getPolicyHolderName(), policy.getCar().getModel(), policy.getCar().getCarType().toString(), policy.getCar().getManufacturingYear() +"", policy.getCar().getPrice() +"", policy.getNumberOfClaims() +"", policy.getExpiryDate().toString(), null, null, null, null };
            if (policy instanceof ThirdPartyPolicy) {
                row[8] = ((ThirdPartyPolicy)policy).comments;
                row[10] = (row[9] = "NA");
            }
            else {
                row[8] = "NA";
                row[9] = ((ComprehensivePolicy)policy).driverAge + "";
                row[10] = ((ComprehensivePolicy)policy).level + "";
            }
            row[11] = String.format("$%.2f", policy.calcPayment(10));
            model.addRow(row);
        }
    }
    
    public void fillTable1() {
        ArrayList<InsurancePolicy> policiesCopy = new ArrayList<>();
        for (final InsurancePolicy policy : user.getPolicies().values()) {
            policiesCopy.add(policy);
        }
        
        try {
            if (!carModelText.getText().isEmpty()) {
                policiesCopy = InsurancePolicy.filterByCarModel(policiesCopy, carModelText.getText());
            }
            if (!expiryDateFilterText.getText().isEmpty()) {
                final String[] fields = this.expiryDateFilterText.getText().split("/");
                final int day = Integer.parseInt(fields[0]);
                final int month = Integer.parseInt(fields[1]);
                final int year = Integer.parseInt(fields[2]);
                final MyDate date = new MyDate(day, month, year);
                policiesCopy = InsurancePolicy.filterByExpiryDate(policiesCopy, date);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        if (sortNameCheckbox.isSelected()) {
           Collections.sort(policiesCopy);
        }
        final String[] header = {"Policy ID", "Policy Holder Name", "Car Model", "Car Type", "Manufacturing Year", "Price", "Number Of Claims", "Expiry Date", "Comments", "Driver Age", "Level", "Premium Payment"};
        final DefaultTableModel model = new DefaultTableModel(header, 0);
        policyTable1.setModel(model);
        for (final InsurancePolicy policy : policiesCopy) {
            final String[] row = { policy.getId() +"", policy.getPolicyHolderName(), policy.getCar().getModel(), policy.getCar().getCarType().toString(), policy.getCar().getManufacturingYear() +"", policy.getCar().getPrice() +"", policy.getNumberOfClaims() +"", policy.getExpiryDate().toString(), null, null, null, null };
            if (policy instanceof ThirdPartyPolicy) {
                row[8] = ((ThirdPartyPolicy)policy).comments;
                row[10] = (row[9] = "NA");
            }
            else {
                row[8] = "NA";
                row[9] = ((ComprehensivePolicy)policy).driverAge + "";
                row[10] = ((ComprehensivePolicy)policy).level + "";
            }
            row[11] = String.format("$%.2f", policy.calcPayment(10));
            model.addRow(row);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FindButton;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel carModelLabel;
    private javax.swing.JTextField carModelText;
    private javax.swing.JCheckBox checkBoxNewCity;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityText;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> comboBoxCity;
    private javax.swing.JLabel commentAgeLabel;
    private javax.swing.JTextField commentAgeText;
    private javax.swing.JRadioButton cpRadio;
    private javax.swing.JTextField dayText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel expiryDateFilterLabel;
    private javax.swing.JTextField expiryDateFilterText;
    private javax.swing.JButton filterDateButton;
    private javax.swing.JButton jButtonChange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAddInfo;
    private javax.swing.JLabel jLabelDay;
    private javax.swing.JLabel jLabelExpiryData;
    private javax.swing.JLabel jLabelPlanID;
    private javax.swing.JLabel jLabelPlcHolderName;
    private javax.swing.JLabel jLabelPolicyID;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JLabel jLabelmanuYear;
    private javax.swing.JPanel jPanelAddPolicies;
    private javax.swing.JPanel jPanelEditPersonalData;
    private javax.swing.JPanel jPanelFilterPolicies;
    private javax.swing.JPanel jPanelFindPolicy;
    private javax.swing.JPanel jPanelPoliciesInformation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField levelText;
    private javax.swing.JMenu logout;
    private javax.swing.JTextField manufacturingYearText;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField modelText;
    private javax.swing.JTextField monthText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField numberOfClaimsText;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passText;
    private javax.swing.JTextField planIDText;
    private javax.swing.JTextArea policyArea;
    private javax.swing.JTextField policyIDText;
    private javax.swing.JTextField policyNameText;
    private javax.swing.JTable policyTable;
    private javax.swing.JTable policyTable1;
    private javax.swing.JTextField priceText;
    private javax.swing.JCheckBox sortNameCheckbox;
    private javax.swing.JLabel strLabel;
    private javax.swing.JLabel strNumLabel;
    private javax.swing.JTextField strNumText;
    private javax.swing.JTextField strText;
    private javax.swing.JLabel suburbLabel;
    private javax.swing.JTextField suburbText;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JRadioButton tppRadio;
    private javax.swing.JComboBox<String> typeCombo;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JTextField userIDText;
    private javax.swing.JTextField usernameText;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables
}
